config/routes.rb
Rails.application.routes.draw do
  root 'checks#new'
  resources :checks
  get '/questions/qoute_question', to: 'questions#show'
  get 'about', to: 'static#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check.rb
class Check < ActiveType::Object
  attribute :question, :string
  attribute :answer, :string
  attribute :right_answer, default: ''
  # attribute :us_sound_link, :string, default: nil

  validates :question, :answer, presence: true
  before_save :sanitize_input

  def errors_array_index
    question.split(' ').each do |q|
      word = Word.find_by_representation(q) || find_in_cambridge_dict(q.tr('’', '-'))
      self.right_answer += word.phonetic + ' '
    end
    self.right_answer.strip!
    errors_index = []
    answer_splits = answer.split(' ')
    self.right_answer.split(' ').each_with_index do |rw_word, i|
      errors_index << i if !answer_splits[i] || rw_word != answer_splits[i]
    end
    errors_index
  end

  private

  def sanitize_input
    self.question = question.downcase.gsub(/[^a-z_ -]/, '').squish
    self.answer   = answer.downcase.squish
  end

  def find_in_cambridge_dict(query)
    doc  = Nokogiri::HTML(HTTParty.get("http://dictionary.cambridge.org/dictionary/english/#{query}"))
    ipas = doc.css('div.di-body').try(:first).try(:css, 'span[pron-region="US"] span.ipa')
    if ipas.blank? || ipas.first.content.blank?
      doc = Nokogiri::HTML(HTTParty.get("http://dict.laban.vn/find?type=1&query=#{query}"))
      ipas = doc.css('div.world span.color-black')
      return Word.new(phonetic: '') if ipas.blank? || ipas.first.content.blank?
    end
    Word.create!(representation: query.tr('-', '’'), phonetic: ipas.first.content)
  end
end

app/models/word.rb
class Word < ApplicationRecord
  validates :representation, :phonetic, presence: true
  validates :representation, :phonetic, uniqueness: true
  before_save :santinize

  private

  def santinize
    self.phonetic = phonetic.tr('t̬', 't').tr('ɝ', 'ɜr').gsub('ɚ', 'ər') \
                            .gsub(%r{[/.\[\]]}, '')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/checks_controller.rb
require 'open-uri'

class ChecksController < ApplicationController
  def new
    build_check
  end

  def create
    build_check
    redirect_to root_path unless @check.save
  end

  private

  def check_params
    params[:check] ? params.require(:check).permit(:question, :answer) : {}
  end

  def build_check
    @check ||= Check.new(check_params || {})
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    load_question
  end

  private

  def load_question
    @doc    ||= Nokogiri::HTML(HTTParty.get("http://livelifehappy.com/page/#{rand(100)}/"))
    @question = @doc.css('article div.entry-content p:nth-child(2)')[rand(4)].content.gsub(/^.*:|–.*$/, '')
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def ipa_keys
    %w(' , a: ai au o: oy ou e ei ea I i: uw u: ^ ow 3: p b f v k ɡ th dd s z sx 3y
       t d tsx d3y j m n ny w r h l)
  end

  def ipa_list
    %w(ˈ ˌ ɑː aɪ aʊ ɔː ɔɪ oʊ e eɪ æ ɪ iː ʊ uː ʌ ə ɜ: p b f v k ɡ θ ð s z ∫ ʒ t d t∫
       dʒ j m n ŋ w r h l)
  end
end

app/views/checks/create.js.erb
<% check_result = @check.errors_array_index %>

$('#result').removeClass();
$('#result').addClass('<%= check_result.blank? ? 'right' : 'wrong' %>');
$('#result').html('<%= html_escape(check_result.blank? ? "Congratulations! You're right." : "Oops! You are wrong somewhere.") %>');

right_answer = '<%= @check.right_answer %>';
errors_index = <%= check_result %>;
right_answer_html = ''
$.each(right_answer.split(" "), function(index, value){
  if (errors_index.indexOf(index) > -1) {
    right_answer_html += "<span class='highlighted'>" + value + '</span> ';
  }
  else {
    right_answer_html += '<span>' + value + ' </span> ';
  }
})
$('#right_ans').html(right_answer_html);

app/views/checks/new.html.erb
<div class="container home">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6">
      <%= form_for @check, remote: true do |form| %>
        <div style="min-height: 6em;">
          <h2><%= t(:question) %>  <a href="#" id="refresh_question"><i class="fa fa-refresh" aria-hidden="true"></i></a></h2>
          <p class="question"></p>
          <%= form.text_field :question, hidden: true  %>
        </div>
        <h2><%= t(:answer) %></h2>
        <%= form.text_area :answer, { rows: 5, required: true, autofocus: true } %>
        <p style="text-align: center; padding-top: 20px; clear: both;">
          <%= form.button t(:check), class: "btn btn-primary"  %>
        </p>
        <div class='checking_loading'>
          <p><%= t(:patient) %></p>
        </div>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6">
      <div class="col-xs-12" style="min-height: 7em;">
        <h2><%= t(:result) %></h2>
        <div class='checking_loading'>
          <p><i class="fa fa-spinner fa-spin fa-2x" aria-hidden="true"></i></p>
        </div>
        <p id="result"></p>
      </div>
      <div class="col-xs-12">
        <h2><%= t(:right_ans) %></h2>
        <div class='checking_loading'>
          <p><i class="fa fa-spinner fa-spin fa-2x" aria-hidden="true"></i></p>
        </div>
        <p id="right_ans"></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <h1 class="center"><%= t(:how_to_use) %></h1>
    </div>
    <div class="col-xs-12">
      <table class="phonetic_keyboard">
        <thead>
          <tr>
            <th>Gõ liên tục</th>
            <% ipa_keys.each do |key| %>
              <th><%= key %></th>
            <% end %>
          </tr>
        </thead>
        <body>
          <tr>
            <td>Hiển thị</td>
            <% ipa_list.each do |phonetic| %>
              <td><%= phonetic %></td>
            <% end %>
          </tr>
        </body>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhoneticPractice</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no" name="viewport">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <i class="fa fa-bars" style="color: white;" aria-hidden="true"></i>
      </button>
      <a class="navbar-brand" href="/">English Phonetic Practice</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right icon-link">
        <li><%= link_to("<i class='fa fa-bug' aria-hidden='true'></i>".html_safe, "url") %></li>
        <li><%= link_to("<i class='fa fa-github' aria-hidden='true'></i>".html_safe, "url") %></li>
        <li><%= link_to("<i class='fa fa-info' aria-hidden='true'></i>".html_safe, about_url) %></li>
      </ul>
    </div>
  </div>
</nav>